using System;
using System.Collections.Generic;
using System.Text;

namespace OrderManager.Core.DTOs
{
    public class OrderDto
    {
        /// <summary>
        /// Autogenerated id for post entity
        /// </summary>
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime? Date { get; set; }
        public string Description { get; set; }
        
    }
}
